name: QEMUWF
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Build
      run: msbuild QEMUWF.sln /p:Configuration=Release /p:platform=x86
    - name: Upload QEMUWF
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: QEMUWF
        # A file, directory or wildcard pattern that describes what to upload
        path: QEMUWF\bin\Release\QEMUWF.exe
